hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "e8530d58ef9e5991e366a56cc4f478a1e35b136255805a965c7021eff5df69d0"

[[files]]
file = "README.md"
hash = "7e830ee560a0d83feaa46e4de97d5bd4383291fc04277d19a8c951bf17a9c448"

[[files]]
file = "config/DistantHorizons.toml"
hash = "1ab54d101fa6e2c96dd168aa10f7e3fbcd24131a4d129f1edd8efe5fa9094024"

[[files]]
file = "config/NoChatReports/NCR-Client.json"
hash = "edfe78d985fe67dce28104f3d87673e94c89134144451c291ecedcd2e2c3b480"

[[files]]
file = "config/NoChatReports/NCR-Common.json"
hash = "0eaad2630bd70ade719f7810e805810ada25379269ea194e43d3eea30c51dec0"

[[files]]
file = "config/NoChatReports/NCR-Encryption.json"
hash = "0f61ac30bfc78653a30d715f793e30a6a43d6715106706487efd0aea5d43a84c"

[[files]]
file = "config/NoChatReports/NCR-ServerPreferences.json"
hash = "df32843b853e0a493ef3a9b1e39276818294353fbb0d833f7f61e77da0f5bca1"

[[files]]
file = "config/NoChatReports/README.md"
hash = "c52b76ccad2bd1063a22c7f6bb9e7c5db6b00fb53a6fd605585972ee0e5fc01f"

[[files]]
file = "config/PaginatedAdvancements.json5"
hash = "7ceeda1666fe67bfa83b1c3b382e589d378149d2b068df7d1e5238f476229e92"

[[files]]
file = "config/appleskin.json5"
hash = "ae87f2d1b38dfd4b1e0767dfeb539261deaaf4fd2eb73692afcbaac7147855b9"

[[files]]
file = "config/balm-common.toml"
hash = "a200148a1d65802310b4a477e2bb76ae4202e16da96edcf62c82ff303911caac"

[[files]]
file = "config/betterf3.json"
hash = "4b9c965fdb8737a322b8ed47cb5cbf67342853e98e582a1f00e656f1c7429260"

[[files]]
file = "config/betterthirdperson.json5"
hash = "151cb9f1ab722aa7026701e482e77cb13eeef2ce7c77cfbac997f719a81b1dbb"

[[files]]
file = "config/c2me.toml"
hash = "81839ac42bacc4e691edad7574a6b4256a9c64bc40595f1b4bcd622a94cf6177"

[[files]]
file = "config/carpet/default_carpet.conf"
hash = "96bb07571d47c44e9508aeb85fa19e2f8926227c533e69e8d3a491d3a860cf42"

[[files]]
file = "config/chunky/config.json"
hash = "c7384a22595488f79f3125b22cc175eb729267267807a084479419349797abc8"

[[files]]
file = "config/chunky/tasks/minecraft/overworld.properties"
hash = "e4f26313b5029d08d719ab953b7a39a7709eb497c7d1cc260e6f9eede509fceb"

[[files]]
file = "config/chunky/tasks/minecraft/the_nether.properties"
hash = "19707b6be65c865c2e97d54d480a76513b64066afe74441ef371f77d0def5afe"

[[files]]
file = "config/citresewn.json"
hash = "d073779d3c9ae385981efa7d1ae7c58ae8f04243ce4d87983eb41f3b6de98f9b"

[[files]]
file = "config/clienttweaks-common.toml"
hash = "916fdc77d8e288a57d479e9f021e5f40558540dce778ffda225be5269dc63204"

[[files]]
file = "config/collective.json5"
hash = "b6243b955bf123f86c947510d9f8f3a4b5f7b8fe3775d834f458d60a3223847f"

[[files]]
file = "config/craftingtweaks-common.toml"
hash = "4af862cd0a1c7c379c40c110d5ddea00e211dec005fb09dcee1bfa490b3682b0"

[[files]]
file = "config/cullleaves.json"
hash = "597892644119cc324a2294077e2c92dcf872e06e8280f0f88bf55a42a36208bf"

[[files]]
file = "config/debugify-descriptions.json"
hash = "3e9b15ba955cb8e4e033a874476adf1eb933ec4d09d0f3ffb8ec7574de3f88d0"

[[files]]
file = "config/dynamic_fps.json"
hash = "e251db8957bf2c69859b49be523dd3f3e278f01d1c08d771d4d3ce6001675c41"

[[files]]
file = "config/e4mc/e4mc.toml"
hash = "6a9c7068c2638733e0dca9c29b52c21847e180092755dcf50c39c1f4ba9a84cb"

[[files]]
file = "config/enhanced_bes.properties"
hash = "dbc7f61d77c0928ea4dfa438fab472620b7363af16e10b02fe2a96c4c098d742"

[[files]]
file = "config/entityculling.json"
hash = "c87799c19ffe3303ce17c6c4e3538a47456e34ecf9830d578535cebf180a77fb"

[[files]]
file = "config/fabric/indigo-renderer.properties"
hash = "2fc9d153034d8bef94658ea39409959875cf0faedb95de059f24c1867ec5d4f7"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "810a1f272f638a2da0de7247a686989c1ad5f227a8db3fe5c592183661467849"

[[files]]
file = "config/fabrishot.properties"
hash = "4b1da543230d1f0567c7ad509da5d9621b2c1be881e48f3dae3342a788bc5d38"

[[files]]
file = "config/fallingtree.json"
hash = "ba56781fa25829a32a2a37c34b31b09ceb4ba8c7312e1cbf1e408d11ae928488"

[[files]]
file = "config/fastquit.toml"
hash = "e85f39867513fe26179ba3cf7a00d343e9642ceaa96e7ea3cde6a1c3aa69dd4e"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "3cc3011619f098fda6ad213a7c4d1468802ff827591a5917c2b7bf3150bfb2ea"

[[files]]
file = "config/firespreadtweaks.json5"
hash = "14ae60dcd9a6e0834f149fa6283ee5333fddaea8e541ed3148732420a424472f"

[[files]]
file = "config/immediatelyfast.json"
hash = "722b612b9b0688a7d5881c5c12182df882bb089f07caf098eb6654d5e6a95b15"

[[files]]
file = "config/jei/blacklist.json"
hash = "b4174dc6e985aa90be5002c14e94b956d8d586683c44b7b6710c44d08fb13648"

[[files]]
file = "config/jei/ingredient-list-mod-sort-order.ini"
hash = "7b9675e46cd53976c10aefb2445417cb2ddb776be876a2b791315ff0be393747"

[[files]]
file = "config/jei/ingredient-list-type-sort-order.ini"
hash = "f6faa8cf111795b26bb59fe7618381fba1879ddc35dbac176297f57941496ff6"

[[files]]
file = "config/jei/jei-client.ini"
hash = "37cf1f682d623a42e9d56b9348a94b12811ffdb18fe6de17d2253b80855ab278"

[[files]]
file = "config/jei/jei-colors.ini"
hash = "e4bc0c5fce5a7536bce14c94b30e30482e65d63792b29db0ad59d4fa9eb4d1a5"

[[files]]
file = "config/jei/jei-debug.ini"
hash = "16bada81bf6ab44c1aa2b60e995833d4c3d6044faf1da7d56fee3c866d0f41ca"

[[files]]
file = "config/jei/jei-mod-id-format.ini"
hash = "4eb3a3eb280558bdd2665fb4792d32551cb6dddc468776e66afc1c3ea981781e"

[[files]]
file = "config/jei/recipe-category-sort-order.ini"
hash = "07273658a6cc8125d39411f7ae5e736607de08423dffdd8d9ef6c1ad6ca00b7f"

[[files]]
file = "config/jei/world/local/mundo-teste-distant-horizons/bookmarks.json"
hash = "36fe8971c1f9dc73d3443d5a5048c125b9ee125d32953505943386fd734ebaad"

[[files]]
file = "config/lighty/base.config"
hash = "3b5909f2b85dd9593a91d3cfb5312a22b50766c8fb01e5930f860a5b9a92cfbb"

[[files]]
file = "config/lithium.properties"
hash = "6cf6f83720071fd1657c8e79b357caf68d40f410ae123e5f922483eb1d1d25be"

[[files]]
file = "config/modelfix-client.json"
hash = "b55936928438ab49ebc8086579cd2218faf14d777fd15ec6eee895dbcadb667d"

[[files]]
file = "config/modernfix-mixins.properties"
hash = "e99bcf13e74d8325b7a2a52c6ac352d4dfc444b83c4047935c4f8e6fe15ef563"

[[files]]
file = "config/modmenu.json"
hash = "16d20c40cc6c114faff5493b561873fe160a65047720bc19fb3a3dd64aa67f3b"

[[files]]
file = "config/moreculling.toml"
hash = "d10d9bd254907b50b3ae0257ca2e95098805b636f95111cf8cfc49ffb42646f5"

[[files]]
file = "config/ping-wheel.json"
hash = "0ac54a90d81c29459c3bf27c390b5d1d868d9dc1a8af8761b220fb3b1cf7570e"

[[files]]
file = "config/ping-wheel.server.json"
hash = "821d5d12d0c096996c82d1a65349ac803adffcc25b89420a146c727fb92b381a"

[[files]]
file = "config/reacharound.json"
hash = "ea97da7a52cfbbb715e51ec2c1b7e2937f9cd6b733fcfc697674ea89bdc04ec8"

[[files]]
file = "config/replantingcrops.json5"
hash = "58ec1ad4dab7ebcd4c7083ad3bfb278812138a5a7590ed91a788508a009b6280"

[[files]]
file = "config/rrls.toml"
hash = "0e4a0d773bc1c38198a52dbc8745f2afabb607e55660cc56c3d4943995c1dab6"

[[files]]
file = "config/sodium-extra-options.json"
hash = "230808b2003c3f049fd79fc3de949e923a4a9d5a23d4f28efe9fa3e3c3bce8af"

[[files]]
file = "config/sodium-extra.properties"
hash = "a2f1b47c1eaa119ab34727f1d43c2506cb3d7f17ba8fb4efb49e20c8e0b58e70"

[[files]]
file = "config/sodium-fingerprint.json"
hash = "1dddc7f22fa36f2110565b391fe8e15a3820ec2865552dec9bb0d0872dfd26ba"

[[files]]
file = "config/sodium-mixins.properties"
hash = "b627c4456e6fa0bc4b5f85e2f1cd949faedae3cb9afdaf2a5f52e6f3b6ae1f01"

[[files]]
file = "config/sodium-options.json"
hash = "545dd7bd8332b89fb316387bb891ca061edba2935e55e41ca2b219dbaf50e7ce"

[[files]]
file = "config/xaerominimap-common.txt"
hash = "b410746ddef0f7dd5f1d860ef3fcd6ad29c10988abbf6281181cb9c3acb628ca"

[[files]]
file = "config/xaerominimap.txt"
hash = "241cf74d8cd67994c6914f29eee8abc1cea14c174cc98504596abf197908f189"

[[files]]
file = "config/xaerominimap_entities.json"
hash = "94fc0e69a1754ef80c54e1f3c9193526c620b0ac646f94a4a0f560bcc58826a8"

[[files]]
file = "config/xaeropatreon.txt"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "config/xaeroworldmap-common.txt"
hash = "ab09b6171d1f5f9c15d3ea653be739b53bca6f88db1ec38ae80575143c4c68cd"

[[files]]
file = "config/xaeroworldmap.txt"
hash = "6cae8c6c64eeebf4dd15076b8f172a440bf1ece460aef63d3abe206e2d45fe8f"

[[files]]
file = "config/yacl.json5"
hash = "d26a63d3cdf326412ba86dcc2781060bc53ed6c74ac7808e65325452e264e820"

[[files]]
file = "config/yigd.json"
hash = "445438e0576218e0dc6a15b6c58686b8da38779e0b3e6215cfee873606fe4bd0"

[[files]]
file = "config/zoomify.json"
hash = "60a78fe1b271ce9b53e295235eb5a7cdb3a8692ca583fdaa7f5bc09f9049e2f4"

[[files]]
file = "datapacks/yigd-grave-recipe.zip"
hash = "59a6aa8fdf290498b4756391454d6040729c5591204e57ed610bf03cc4673850"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "3fab60aca0fee9153c49b40e1b06b1deebb23800dce7b8b8f471e23f43f3efe5"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "17fc9c6cab5ae0ea6973440f143ad6ffa4e5d373749c80077b631dbbe4df3f3b"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "6e39e7712a94830fbc2bd0b6ec73e03f54de5edfcca85da6e89a0021e9a3bf1a"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "7c45c50ac2431db0dd3697e16a180a55ac0f2a753540b0bd310eb593b8b0bd0a"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "dd18db1413980ef467ac2e86c7e5f3cef26d366119f43121204a442583e7c0bd"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "7d1815ec4f2098c4de8b01494373d84da8a5104accd5ae028a2a020595646082"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "941c3f358ef74f4fc99727e550106b8905d77cb4971321fd8ca4406e33b704a6"
metafile = true

[[files]]
file = "mods/carpet-extra.pw.toml"
hash = "54f2b9609b14158941951ca10de56d5efa478b88a3a25ad5390bebbefcd08ff9"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "a059d2d23cd47fe2e698f06826a1053a39599f74fb1b739c622754630f90086c"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "1ba7fcf69deeec5536f8c9e43ee4527a5871e9e5805c1801b855e5c00b25d05a"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "7fe287ca1bed0ad67f37e62a5816da7b7ae59486102c5e4b7532f0a999444527"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "6d511d91e17e09d36b0b0c7065b07eb604146bc9f3df0fbc932948aaf33aa440"
metafile = true

[[files]]
file = "mods/client-tweaks.pw.toml"
hash = "1522700593fa70f7f2aa9042cc7ec5cb3c93c95bbc634930e8f15717dace9ce2"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "fe84e2227c405bf9b735f01f307a01768784b9d49df82a13ecda3d3b6d198507"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "cde21d14fcaf9495f0f5b3d8fb298dd60cb12badc21a27414c25ebf11dfb3fe1"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "4f97764f3cb4c74f84afbe32cf8a1d2cefecda129c0f1441906562dcb8f2b8cb"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "eecdc8127f69c74ff55fd183d1f1d7d5ef3e714d73845a239fe9e086147a67b1"
metafile = true

[[files]]
file = "mods/crafting-tweaks.pw.toml"
hash = "25c69b6d03bd0cd0ad66a6b44af07dbe748bf008300abbde356b7775259b590f"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "31535a06bf76553e83bd982eb3df9158b815cb7d0207a3fc719758d020d683b7"
metafile = true

[[files]]
file = "mods/cull-leaves.pw.toml"
hash = "2f62ae4c00af9ef9bdb8cae7c66b4eac578612dc5bf35bc33ffa0b9f9db09759"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "7cb9e98526468233fbec6f949c78a8afc5ef29447868e1d11cb71293237966a2"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "09601787ecf7b39bd637b57ce711da79f1e1b9e677d3a654c112b0badf90ea17"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "4effaea1cdc0ccd0de4a94ab435cc3cb22085933fca7e1dd35b9fb8953a1ce9e"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "d26d9c0a67fa27dfe192dac7e75d2b0b598ea6c4f0390ca434f3e50d653d44d0"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "b1f89407254a20cde6c60994a6315bd841b7f562669a1d29b436ec97463ff2ae"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "52eff5c4364676432feed4f4ea8b8a9441d4d95b84d4c434891063c99c05029c"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "446f8047ee9168b65fe9d4600f82cb915c7aa0d0f049a344177ba340a5b93a8a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fabricskyboxes-interop.pw.toml"
hash = "556fddf5f52f49d9acf41e4db737e5431c1b45e60f5e0c04ca1de70b01dd1d15"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "c78c2d26feb460adb112cda9ec5073f8968298f1d215eb8679fd67f55f3c3124"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "b062d71c371b3361e700edb4db46acd1a1feed6c91b95764e08e03cdb25ba1f5"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "f9f1e1c017e7b902531a68a3f8c9650a18a40a8ab9f0bf44ef5af08b37da8aaf"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "4387abb74dcfc93f9381c109fe76e7161ca7a91a1a642db4781b47f650c4ddab"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "9fb4d588bd578e2f16a9605ff6303872130b36ccb0fdfff98bd7274da94f91b9"
metafile = true

[[files]]
file = "mods/fire-spread-tweaks.pw.toml"
hash = "88c4b934a719f68034b5248d171900c019a8128c0a6929f474d6987a7ac22757"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "37e14a7a0b033feafd7fc1cb82842c128b1b2f2053dd1d11206834d7fcc6f597"
metafile = true

[[files]]
file = "mods/inventory-essentials.pw.toml"
hash = "652d7f476f9ae3d69fe6abb51d5eaa171955752a0bd29eb4fec3da3a3157d153"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "473ff38fda137819bfe305514a5a99cf962cd7a13694049cb79c477d93310c44"
metafile = true

[[files]]
file = "mods/kiss.pw.toml"
hash = "de1944f9e22b5ebc1df0e2ceb10a81ec8148c771d18382141fc4e15e0dd00a2f"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
hash = "237f61291d7f6cbfe8bafd6fc22657000adc2b8de269061eb81b6eb21d3ea5d1"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "5564dbbe8adc0ba450afc6a1c3eef82f183a53ede5f3b1de0bc6ca320aadc5e9"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "d9221689ffa47dcd27e6c0590ba7b3227f83d48a6e9592cd09e1835f143d793a"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "0d85e3cfa3a0d0b99f650afd2301f95edf02b3eba6dd7679bf16eb3872331170"
metafile = true

[[files]]
file = "mods/mobexplosiongriefinggamerule.pw.toml"
hash = "8a4dd44991a4fdea28ac9d4c1cd229399e359dccb2896214d083eb0bc391aa71"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "d12b136e07f6f83a1e199aabe430426d19702c9f69e55731092b5d5c2f3fb69f"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "b9651d06e56ad51c1cdcf4b03b6a34328b7dc941f263ff92b189ee26a47cc224"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d917697e84a95f857a447d26f94d93169a5a62176c93193cdf80c8d8bc1e280a"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "096bce1d87ff7f759d07ae6501043c5d2db1bcdffb5ea566425843f12ff8e348"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "6be43ffc708ac329843aee99ededc692ecf6461ee8e409d373f55fc5494db5af"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "f3c5cb21ff2e78c7e8cdbd14d1535e6edd464d5a436dbfa4e60b8ea91374674d"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "dcc936d7bd32a86ce63fa3bf013864a4e2ed979cb126a915153ac70ce5e5671f"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "110132a70b524eaadb750bc110c9344d84432da97a5434ae185e815d778d21f0"
metafile = true

[[files]]
file = "mods/ping-wheel.pw.toml"
hash = "f1746f7abc78b5a149212d295b903cfc232477b1abd9e2050e5d4af3acc530b5"
metafile = true

[[files]]
file = "mods/reacharound.pw.toml"
hash = "f5aa8a4410d84e6ab5dd3797e2b900b26f669bd801ace7aab19ed987c4a05001"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "55a727cabdd9d6e84fb0232b49d0dfa207751002e7f1f63b959baa35e2f29868"
metafile = true

[[files]]
file = "mods/replanting-crops.pw.toml"
hash = "f18f0527040db10a15a333f0d02d8c627b2b6b684c8aa3536982bc36592498ae"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "59943cbd2c0e4e90f65002e17704bca571acb09b095fc69fdf430df4bfd42870"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "8302da862578554b012b2cfe58a3c1e75b514d09f94d842e7303be41a2157aeb"
metafile = true

[[files]]
file = "mods/servux.pw.toml"
hash = "dd6b8593c63f56146cae995ca8ce8a8f073eaa6869376acc7c2473920d38e3af"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "0d51bf2566f8057955226b2bc0ddf7b404d581304dcf163139e1b4fb6ac2fc7e"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "1af09f16a643df0f61f2c799e981aa0b8c109999f0784584a6eff9a81f1c00c1"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "745e9e9a29f81b00070fa39bc86c543d39b54e1e4786f8353bb51351f06667ad"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "930c62a2d832d9b9dac1637a89265415007eba0033e84cbc1b9b80bd6f483554"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "2d0ca6e5a2077ae624a65a5310f36ddd6736de699748ac3959022e03844e2f52"
metafile = true

[[files]]
file = "mods/yigd.pw.toml"
hash = "5be05538347e59b65357ecb31c28c90edd3769309fa864222d7116ccd7e8a446"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "fb09f6357ae2e3dcfea36520efde6e9b761efffc63b4dfdec5e4b11011bac58c"
metafile = true

[[files]]
file = "options.txt"
hash = "5be26d487f25e957c53bb80d64e1b2e4cc77df45b16868e3a1f288e6ed90b8b5"

[[files]]
file = "resourcepacks/better-leaves.pw.toml"
hash = "f23b343e4a4555895e697c5ce98971809056a721e4732e25ea5b6952d91c0180"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "19e48b773677cc0d4a448e7ec5f4d82d7c9bd21063aac3c1bf710b4a78865c53"
metafile = true

[[files]]
file = "resourcepacks/fast-better-grass.pw.toml"
hash = "b6643cac68927881baa84fa7f348a2d60b6d2f901b4612c7a8c4ad882f90f23b"
metafile = true

[[files]]
file = "resourcepacks/hyper-realistic-sky.pw.toml"
hash = "ad6e0d24cb0fd6dc920a404362f7c005cbcb760caf3250a76e73b9e2050fd32e"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "347564c7db8830d5595e0c6cc3b7c4bb9d040cfd09272d672a969200cb24d3d0"
metafile = true

[[files]]
file = "resourcepacks/unique-enchanted-books.pw.toml"
hash = "4f89cd43a057cb838d6ecbf5e6cfdedd4ebff2a471328e9041a618c5e877d49d"
metafile = true
