name = "Modpack Pre Residencia"
author = "MestreProno"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2942b78fe00acb437589187bc9fc4f1e9d2635c5c2143bbf03cbe85f6e3bcfe4"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
